// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: articlecrawler.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleCrawler_SubmitURLs_FullMethodName    = "/articlecrawler.ArticleCrawler/SubmitURLs"
	ArticleCrawler_GetArticle_FullMethodName    = "/articlecrawler.ArticleCrawler/GetArticle"
	ArticleCrawler_ListArticles_FullMethodName  = "/articlecrawler.ArticleCrawler/ListArticles"
	ArticleCrawler_DeleteArticle_FullMethodName = "/articlecrawler.ArticleCrawler/DeleteArticle"
)

// ArticleCrawlerClient is the client API for ArticleCrawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleCrawlerClient interface {
	// принимает список URL возвращает список принятых не успешно
	SubmitURLs(ctx context.Context, in *SubmitURLsRequest, opts ...grpc.CallOption) (*SubmitURLsResponse, error)
	// получить статью по ID
	GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error)
	// получить список всех статей или последних N
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
	// удалить статью по ID
	DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
}

type articleCrawlerClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleCrawlerClient(cc grpc.ClientConnInterface) ArticleCrawlerClient {
	return &articleCrawlerClient{cc}
}

func (c *articleCrawlerClient) SubmitURLs(ctx context.Context, in *SubmitURLsRequest, opts ...grpc.CallOption) (*SubmitURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitURLsResponse)
	err := c.cc.Invoke(ctx, ArticleCrawler_SubmitURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleCrawlerClient) GetArticle(ctx context.Context, in *GetArticleRequest, opts ...grpc.CallOption) (*GetArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleResponse)
	err := c.cc.Invoke(ctx, ArticleCrawler_GetArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleCrawlerClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, ArticleCrawler_ListArticles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleCrawlerClient) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleResponse)
	err := c.cc.Invoke(ctx, ArticleCrawler_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleCrawlerServer is the server API for ArticleCrawler service.
// All implementations must embed UnimplementedArticleCrawlerServer
// for forward compatibility.
type ArticleCrawlerServer interface {
	// принимает список URL возвращает список принятых не успешно
	SubmitURLs(context.Context, *SubmitURLsRequest) (*SubmitURLsResponse, error)
	// получить статью по ID
	GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error)
	// получить список всех статей или последних N
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
	// удалить статью по ID
	DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error)
	mustEmbedUnimplementedArticleCrawlerServer()
}

// UnimplementedArticleCrawlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleCrawlerServer struct{}

func (UnimplementedArticleCrawlerServer) SubmitURLs(context.Context, *SubmitURLsRequest) (*SubmitURLsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitURLs not implemented")
}
func (UnimplementedArticleCrawlerServer) GetArticle(context.Context, *GetArticleRequest) (*GetArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedArticleCrawlerServer) ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedArticleCrawlerServer) DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedArticleCrawlerServer) mustEmbedUnimplementedArticleCrawlerServer() {}
func (UnimplementedArticleCrawlerServer) testEmbeddedByValue()                        {}

// UnsafeArticleCrawlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleCrawlerServer will
// result in compilation errors.
type UnsafeArticleCrawlerServer interface {
	mustEmbedUnimplementedArticleCrawlerServer()
}

func RegisterArticleCrawlerServer(s grpc.ServiceRegistrar, srv ArticleCrawlerServer) {
	// If the following call pancis, it indicates UnimplementedArticleCrawlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleCrawler_ServiceDesc, srv)
}

func _ArticleCrawler_SubmitURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCrawlerServer).SubmitURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCrawler_SubmitURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCrawlerServer).SubmitURLs(ctx, req.(*SubmitURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleCrawler_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCrawlerServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCrawler_GetArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCrawlerServer).GetArticle(ctx, req.(*GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleCrawler_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCrawlerServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCrawler_ListArticles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCrawlerServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleCrawler_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCrawlerServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCrawler_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCrawlerServer).DeleteArticle(ctx, req.(*DeleteArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleCrawler_ServiceDesc is the grpc.ServiceDesc for ArticleCrawler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleCrawler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articlecrawler.ArticleCrawler",
	HandlerType: (*ArticleCrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitURLs",
			Handler:    _ArticleCrawler_SubmitURLs_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _ArticleCrawler_GetArticle_Handler,
		},
		{
			MethodName: "ListArticles",
			Handler:    _ArticleCrawler_ListArticles_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _ArticleCrawler_DeleteArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "articlecrawler.proto",
}
