// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: articlecrawler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitURLsRequest) Reset() {
	*x = SubmitURLsRequest{}
	mi := &file_articlecrawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitURLsRequest) ProtoMessage() {}

func (x *SubmitURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitURLsRequest.ProtoReflect.Descriptor instead.
func (*SubmitURLsRequest) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitURLsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type SubmitURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FailedUrls    []string               `protobuf:"bytes,1,rep,name=failed_urls,json=failedUrls,proto3" json:"failed_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitURLsResponse) Reset() {
	*x = SubmitURLsResponse{}
	mi := &file_articlecrawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitURLsResponse) ProtoMessage() {}

func (x *SubmitURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitURLsResponse.ProtoReflect.Descriptor instead.
func (*SubmitURLsResponse) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitURLsResponse) GetFailedUrls() []string {
	if x != nil {
		return x.FailedUrls
	}
	return nil
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_articlecrawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_articlecrawler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           bool                   `protobuf:"varint,1,opt,name=all,proto3" json:"all,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_articlecrawler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{4}
}

func (x *ListArticlesRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *ListArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_articlecrawler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_articlecrawler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_articlecrawler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Html          string                 `protobuf:"bytes,5,opt,name=html,proto3" json:"html,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_articlecrawler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_articlecrawler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_articlecrawler_proto_rawDescGZIP(), []int{8}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *Article) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_articlecrawler_proto protoreflect.FileDescriptor

const file_articlecrawler_proto_rawDesc = "" +
	"\n" +
	"\x14articlecrawler.proto\x12\x0earticlecrawler\"'\n" +
	"\x11SubmitURLsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"5\n" +
	"\x12SubmitURLsResponse\x12\x1f\n" +
	"\vfailed_urls\x18\x01 \x03(\tR\n" +
	"failedUrls\"%\n" +
	"\x11GetArticleRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"G\n" +
	"\x12GetArticleResponse\x121\n" +
	"\aarticle\x18\x01 \x01(\v2\x17.articlecrawler.ArticleR\aarticle\"=\n" +
	"\x13ListArticlesRequest\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"K\n" +
	"\x14ListArticlesResponse\x123\n" +
	"\barticles\x18\x01 \x03(\v2\x17.articlecrawler.ArticleR\barticles\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04html\x18\x05 \x01(\tR\x04html\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt2\xfb\x02\n" +
	"\x0eArticleCrawler\x12U\n" +
	"\n" +
	"SubmitURLs\x12!.articlecrawler.SubmitURLsRequest\x1a\".articlecrawler.SubmitURLsResponse\"\x00\x12U\n" +
	"\n" +
	"GetArticle\x12!.articlecrawler.GetArticleRequest\x1a\".articlecrawler.GetArticleResponse\"\x00\x12[\n" +
	"\fListArticles\x12#.articlecrawler.ListArticlesRequest\x1a$.articlecrawler.ListArticlesResponse\"\x00\x12^\n" +
	"\rDeleteArticle\x12$.articlecrawler.DeleteArticleRequest\x1a%.articlecrawler.DeleteArticleResponse\"\x00B-Z+github.com/kiyotaka137/ArticleCrawler/protob\x06proto3"

var (
	file_articlecrawler_proto_rawDescOnce sync.Once
	file_articlecrawler_proto_rawDescData []byte
)

func file_articlecrawler_proto_rawDescGZIP() []byte {
	file_articlecrawler_proto_rawDescOnce.Do(func() {
		file_articlecrawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articlecrawler_proto_rawDesc), len(file_articlecrawler_proto_rawDesc)))
	})
	return file_articlecrawler_proto_rawDescData
}

var file_articlecrawler_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_articlecrawler_proto_goTypes = []any{
	(*SubmitURLsRequest)(nil),     // 0: articlecrawler.SubmitURLsRequest
	(*SubmitURLsResponse)(nil),    // 1: articlecrawler.SubmitURLsResponse
	(*GetArticleRequest)(nil),     // 2: articlecrawler.GetArticleRequest
	(*GetArticleResponse)(nil),    // 3: articlecrawler.GetArticleResponse
	(*ListArticlesRequest)(nil),   // 4: articlecrawler.ListArticlesRequest
	(*ListArticlesResponse)(nil),  // 5: articlecrawler.ListArticlesResponse
	(*DeleteArticleRequest)(nil),  // 6: articlecrawler.DeleteArticleRequest
	(*DeleteArticleResponse)(nil), // 7: articlecrawler.DeleteArticleResponse
	(*Article)(nil),               // 8: articlecrawler.Article
}
var file_articlecrawler_proto_depIdxs = []int32{
	8, // 0: articlecrawler.GetArticleResponse.article:type_name -> articlecrawler.Article
	8, // 1: articlecrawler.ListArticlesResponse.articles:type_name -> articlecrawler.Article
	0, // 2: articlecrawler.ArticleCrawler.SubmitURLs:input_type -> articlecrawler.SubmitURLsRequest
	2, // 3: articlecrawler.ArticleCrawler.GetArticle:input_type -> articlecrawler.GetArticleRequest
	4, // 4: articlecrawler.ArticleCrawler.ListArticles:input_type -> articlecrawler.ListArticlesRequest
	6, // 5: articlecrawler.ArticleCrawler.DeleteArticle:input_type -> articlecrawler.DeleteArticleRequest
	1, // 6: articlecrawler.ArticleCrawler.SubmitURLs:output_type -> articlecrawler.SubmitURLsResponse
	3, // 7: articlecrawler.ArticleCrawler.GetArticle:output_type -> articlecrawler.GetArticleResponse
	5, // 8: articlecrawler.ArticleCrawler.ListArticles:output_type -> articlecrawler.ListArticlesResponse
	7, // 9: articlecrawler.ArticleCrawler.DeleteArticle:output_type -> articlecrawler.DeleteArticleResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_articlecrawler_proto_init() }
func file_articlecrawler_proto_init() {
	if File_articlecrawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articlecrawler_proto_rawDesc), len(file_articlecrawler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articlecrawler_proto_goTypes,
		DependencyIndexes: file_articlecrawler_proto_depIdxs,
		MessageInfos:      file_articlecrawler_proto_msgTypes,
	}.Build()
	File_articlecrawler_proto = out.File
	file_articlecrawler_proto_goTypes = nil
	file_articlecrawler_proto_depIdxs = nil
}
