// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: pkg/proto/crawler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUrlRequest) Reset() {
	*x = SubmitUrlRequest{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUrlRequest) ProtoMessage() {}

func (x *SubmitUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUrlRequest.ProtoReflect.Descriptor instead.
func (*SubmitUrlRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitUrlRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SubmitUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUrlResponse) Reset() {
	*x = SubmitUrlResponse{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUrlResponse) ProtoMessage() {}

func (x *SubmitUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUrlResponse.ProtoReflect.Descriptor instead.
func (*SubmitUrlResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitUrlResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubmitUrlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *GetArticleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{3}
}

func (x *ListArticlesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Article struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body            string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Summary         string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	ContentHash     string                 `protobuf:"bytes,6,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Language        string                 `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	ReadTimeMinutes int32                  `protobuf:"varint,8,opt,name=read_time_minutes,json=readTimeMinutes,proto3" json:"read_time_minutes,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{4}
}

func (x *Article) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Article) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Article) GetReadTimeMinutes() int32 {
	if x != nil {
		return x.ReadTimeMinutes
	}
	return 0
}

func (x *Article) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type StreamNewArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNewArticlesRequest) Reset() {
	*x = StreamNewArticlesRequest{}
	mi := &file_pkg_proto_crawler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNewArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNewArticlesRequest) ProtoMessage() {}

func (x *StreamNewArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_crawler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNewArticlesRequest.ProtoReflect.Descriptor instead.
func (*StreamNewArticlesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_crawler_proto_rawDescGZIP(), []int{6}
}

var File_pkg_proto_crawler_proto protoreflect.FileDescriptor

const file_pkg_proto_crawler_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/crawler.proto\x12\x05proto\"$\n" +
	"\x10SubmitUrlRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"=\n" +
	"\x11SubmitUrlResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x13ListArticlesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xf9\x01\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12!\n" +
	"\fcontent_hash\x18\x06 \x01(\tR\vcontentHash\x12\x1a\n" +
	"\blanguage\x18\a \x01(\tR\blanguage\x12*\n" +
	"\x11read_time_minutes\x18\b \x01(\x05R\x0freadTimeMinutes\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"B\n" +
	"\x14ListArticlesResponse\x12*\n" +
	"\barticles\x18\x01 \x03(\v2\x0e.proto.ArticleR\barticles\"\x1a\n" +
	"\x18StreamNewArticlesRequest2\x92\x02\n" +
	"\aCrawler\x12>\n" +
	"\tSubmitUrl\x12\x17.proto.SubmitUrlRequest\x1a\x18.proto.SubmitUrlResponse\x126\n" +
	"\n" +
	"GetArticle\x12\x18.proto.GetArticleRequest\x1a\x0e.proto.Article\x12G\n" +
	"\fListArticles\x12\x1a.proto.ListArticlesRequest\x1a\x1b.proto.ListArticlesResponse\x12F\n" +
	"\x11StreamNewArticles\x12\x1f.proto.StreamNewArticlesRequest\x1a\x0e.proto.Article0\x01B7Z5github.com/kiyotaka137/articlecrawler/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_crawler_proto_rawDescOnce sync.Once
	file_pkg_proto_crawler_proto_rawDescData []byte
)

func file_pkg_proto_crawler_proto_rawDescGZIP() []byte {
	file_pkg_proto_crawler_proto_rawDescOnce.Do(func() {
		file_pkg_proto_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_crawler_proto_rawDesc), len(file_pkg_proto_crawler_proto_rawDesc)))
	})
	return file_pkg_proto_crawler_proto_rawDescData
}

var file_pkg_proto_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_crawler_proto_goTypes = []any{
	(*SubmitUrlRequest)(nil),         // 0: proto.SubmitUrlRequest
	(*SubmitUrlResponse)(nil),        // 1: proto.SubmitUrlResponse
	(*GetArticleRequest)(nil),        // 2: proto.GetArticleRequest
	(*ListArticlesRequest)(nil),      // 3: proto.ListArticlesRequest
	(*Article)(nil),                  // 4: proto.Article
	(*ListArticlesResponse)(nil),     // 5: proto.ListArticlesResponse
	(*StreamNewArticlesRequest)(nil), // 6: proto.StreamNewArticlesRequest
}
var file_pkg_proto_crawler_proto_depIdxs = []int32{
	4, // 0: proto.ListArticlesResponse.articles:type_name -> proto.Article
	0, // 1: proto.Crawler.SubmitUrl:input_type -> proto.SubmitUrlRequest
	2, // 2: proto.Crawler.GetArticle:input_type -> proto.GetArticleRequest
	3, // 3: proto.Crawler.ListArticles:input_type -> proto.ListArticlesRequest
	6, // 4: proto.Crawler.StreamNewArticles:input_type -> proto.StreamNewArticlesRequest
	1, // 5: proto.Crawler.SubmitUrl:output_type -> proto.SubmitUrlResponse
	4, // 6: proto.Crawler.GetArticle:output_type -> proto.Article
	5, // 7: proto.Crawler.ListArticles:output_type -> proto.ListArticlesResponse
	4, // 8: proto.Crawler.StreamNewArticles:output_type -> proto.Article
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_crawler_proto_init() }
func file_pkg_proto_crawler_proto_init() {
	if File_pkg_proto_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_crawler_proto_rawDesc), len(file_pkg_proto_crawler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_crawler_proto_goTypes,
		DependencyIndexes: file_pkg_proto_crawler_proto_depIdxs,
		MessageInfos:      file_pkg_proto_crawler_proto_msgTypes,
	}.Build()
	File_pkg_proto_crawler_proto = out.File
	file_pkg_proto_crawler_proto_goTypes = nil
	file_pkg_proto_crawler_proto_depIdxs = nil
}
